version: "3"

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart-policy:
      condition: none

  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    working_dir: /home/node/app
    container_name: app
    ports:
      - 3000:3000
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    depends_on:
      - postgres
    command: npm run dev
    restart-policy:
      condition: none

volumes:
  postgres-data:

